name: Dart

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Analyze
        run: dart analyze

      - name: Run tests
        # We need a dbus session for integration tests
        run: |
            sudo apt-get update && sudo apt-get install -y dbus-x11
            dbus-run-session -- dart test
